/*

 EX3.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 16 x 16
  Tiles                : 0 to 3

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __ex3_h_INCLUDE
#define __ex3_h_INCLUDE

/* Bank of tiles. */
#define Ex3Bank 0
/* Start of tile array. */
extern const unsigned char Ex3[];

#endif

/* End of EX3.H */
