/*

 BACKGROUND1.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 32
   Tile set      : Z:\home\milan\Documents\gameboy\testiprojekti\data\backgroundtiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 37
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __background1_h_INCLUDE
#define __background1_h_INCLUDE

#define background1Width 32
#define background1Height 32
#define background1Bank 0

extern const unsigned char background1[];

#endif

/* End of BACKGROUND1.H */
