/*

 ENEMY1.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
const unsigned char enemy1[] =
{
  0x66,0x24,0xE7,0x66,0xF7,0xE7,0x1C,0x18,
  0x38,0x18,0xEF,0xE7,0xE7,0x66,0x66,0x24
};

/* End of ENEMY1.C */
