/*

 BACKGROUND3.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 32
   Tile set      : Z:\home\milan\Documents\gameboy\testiprojekti\src\data\backgroundtiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 37
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __background3_h_INCLUDE
#define __background3_h_INCLUDE

#define background3Width 32
#define background3Height 32
#define background3Bank 0

extern const unsigned char background3[];

#endif

/* End of BACKGROUND3.H */
