/*

 BACKGROUND2.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 32
   Tile set      : backgroundtiles2.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 37
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __background2_h_INCLUDE
#define __background2_h_INCLUDE

#define background2Width 32
#define background2Height 32
#define background2Bank 0

extern const unsigned char background2[];

#endif

/* End of BACKGROUND2.H */
