/*

 BACKGROUND4.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 32
   Tile set      : Z:\home\milan\Documents\gameboy\testiprojekti\src\data\backgroundtiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 37
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __background4_h_INCLUDE
#define __background4_h_INCLUDE

#define background4Width 32
#define background4Height 32
#define background4Bank 0

extern const unsigned char background4[];

#endif

/* End of BACKGROUND4.H */
