/*

 MARSBACKGROUND.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 32
   Tile set      : marstileset.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 37
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __marsbackground_h_INCLUDE
#define __marsbackground_h_INCLUDE

#define marsbackgroundWidth 32
#define marsbackgroundHeight 32
#define marsbackgroundBank 0

extern const unsigned char marsbackground[];

#endif

/* End of MARSBACKGROUND.H */
